assets: 'assets'
data_path:
  train: '/home/therock/data6/data_workset/dfdc/train/'
  valid: '/home/therock/data6/data_workset/dfdc/valid/'
  test: '/home/therock/data6/data_workset/dfdc/test/'
  train_backup: '/home/therock/data5/dataset_master/deepfake_dfdc/train/'
  train_labels_csv_filename: 'train_labels.csv'
  valid_labels_csv_filename: 'labels.csv'
  test_labels_csv_filename: 'labels.csv'
  processed_train_filename: 'processed_train_samples.pkl'
  processed_valid_filename: 'processed_valid_samples.pkl'
  processed_test_filename: 'processed_test_samples.pkl'
  train_frame_label: 'train_frame_label.csv'
  valid_frame_label: 'valid_frame_label.csv'
  test_frame_label: 'test_frame_label.csv'
  train_faces_count: 'train_faces_count.csv'
  valid_faces_count: 'valid_faces_count.csv'
  test_faces_count: 'test_faces_count.csv'
  train_optframe_label: 'train_optframe_label.csv'
  valid_optframe_label: 'valid_optframe_label.csv'
  test_optframe_label: 'test_optframe_label.csv'
data_augmentation:
  plan_pkl_filename: 'data_augmentation_plan.pkl'
  plan_txt_filename: 'data_augmentation_plan.txt'
  metadata: 'aug_metadata'
  compression_csv_filename: 'data_compression.csv'
  integrity_csv_filename: 'data_integrity.csv'
features:
  train_json_faces: '/home/therock/data2/data_workset/dfdc/json_faces/train/'
  valid_json_faces: '/home/therock/data2/data_workset/dfdc/json_faces/valid/'
  test_json_faces: '/home/therock/data2/data_workset/dfdc/json_faces/test/'
  train_crop_faces: '/home/therock/data2/data_workset/dfdc/crop_faces/train/'
  valid_crop_faces: '/home/therock/data2/data_workset/dfdc/crop_faces/valid/'
  test_crop_faces: '/home/therock/data2/data_workset/dfdc/crop_faces/test/'
  train_faces_cnn: '/home/therock/data2/data_workset/dfdc/faces_cnn/train/'
  valid_faces_cnn: '/home/therock/data2/data_workset/dfdc/faces_cnn/valid/'
  test_faces_cnn: '/home/therock/data2/data_workset/dfdc/faces_cnn/test/'
  train_optical_flow: '/home/therock/data2/data_workset/dfdc/optical_flow/train/'
  valid_optical_flow: '/home/therock/data2/data_workset/dfdc/optical_flow/valid/'
  test_optical_flow: '/home/therock/data2/data_workset/dfdc/optical_flow/test/'
  train_optical_png: '/home/therock/data2/data_workset/dfdc/optical_png/train/'
  valid_optical_png: '/home/therock/data2/data_workset/dfdc/optical_png/valid/'
  test_optical_png: '/home/therock/data2/data_workset/dfdc/optical_png/test/'
  face_location_video_data_path: 'face_location_video_data'
cnn_encoder:
  default: 'tf_efficientnet_b0_ns'
training:
  train_size: 1
  valid_size: 1
  test_size: 1
  checkpoint_path: 'checkpoints'
  params:
    model_name: 'DeepFakeDetectModel_6'
    train_transform: 'simple'
    #train_transform: 'complex'
    batch_format: 'simple'
    #batch_format: 'stacked'
    epochs: 20
    learning_rate: 0.001
    batch_size: 128
    fp16: True
    opt_level: 'O0'
    dataset: 'optical'
    #dataset: 'plain'
logging:
  root_log_dir: logs
  line_len: 80
  model_info_log: 'model_info_and_results.log'
  model_loss_info_log: 'model_losses.log'
  model_acc_info_log: 'model_acc.log'
  model_conf_matrix_csv: 'confusion_matrix.csv'
  model_conf_matrix_png: 'confusion_matrix.png'
  model_conf_matrix_normalized_csv: 'confusion_matrix_normalized.csv'
  model_conf_matrix_normalized_png: 'confusion_matrix_normalized.png'
  model_accuracy_png: 'model_accuracy.png'
  model_loss_png: 'model_loss.png'
  all_samples_pred_csv: 'all_samples_pred.csv'

