logging:
  root_log_dir: logs
printing:
  line_len: 80
assets: 'assets'
data_path:
  train: '/home/therock/data2/data_workset/dfdc/train/'
  test: '/home/therock/data2/data_workset/dfdc/test/'
  validation: '/home/therock/data2/data_workset/dfdc/validation/'
  train_backup: '/home/therock/data5/dataset_master/deepfake_dfdc/train/'
data_augmentation:
  plan_pkl_file: 'data_augmentation_plan.pkl'
  plan_txt_file: 'data_augmentation_plan.txt'
  metadata_folder: 'aug_metadata'
  compression_csv: 'data_compression.csv'
  integrity_csv: 'data_integrity.csv'
features:
  face_location_data_path: 'face_location_data'
  face_location_video_data_path: 'face_location_video_data'